name: Deploy Nightly

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fuzz-directory:
          - fuzz-rust

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and Push Docker Image for ${{ matrix.fuzz-directory }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.fuzz-directory }}
          push: true
          file: ${{ matrix.fuzz-directory }}/Dockerfile
          tags: ghcr.io/nottirb/${{ matrix.fuzz-directory }}:latest
