name: Deploy Nightly

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fuzz-directory:
          - fuzz-rust
          - fuzz-env

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for ${{ matrix.fuzz-directory }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.fuzz-directory }}
          push: true
          file: ${{ matrix.fuzz-directory }}/Dockerfile
          tags: ghcr.io/nottirb/${{ matrix.fuzz-directory }}:latest
